---

- name: Install OpenJDK
  become: yes
  apt:
    name: openjdk-7-jre-headless

- name: Ensure install folders
  become: yes
  become_user: "{{ kafka.user }}"
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "/home/{{ kafka.user }}/tmp"

- name: Fetch kafka binary package
  become: yes
  become_user: "{{ kafka.user }}"
  get_url:
    dest: "/home/{{ kafka.user }}/tmp/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"
    url: "{{ kafka.apache_mirror }}/kafka/{{ kafka.version_kafka }}/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"

- name: Uncompress the kafka tar
  become: yes
  unarchive:
    copy: no
    group: "{{ kafka.user }}"
    owner: "{{ kafka.user }}"
    creates: "/opt/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}"
    dest: "/opt/"
    src: "/home/{{ kafka.user }}/tmp/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"

- name: Create data & log paths
  become: yes
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ kafka.user }}"
    group: "{{ kafka.user }}"
  with_items:
    - "{{ kafka_path }}/log"
    - "{{ kafka_path }}/data"

- name: Remove lost+found in the datadir
  become: yes
  file:
    path: "{{ kafka_path }}/data/lost+found"
    state: absent