---

- name: Overwrite the start script so the Java Opts can be changed if Kafka 0.8.1.1
  become: yes
  lineinfile:
    dest: "{{ kafka_path }}/bin/kafka-server-start.sh"
    regexp: "^export KAFKA_HEAP_OPTS="
    line: "export KAFKA_HEAP_OPTS=\"{{ kafka_heap_opts }}\""
  notify:
    - restart kafka
  when: kafka_version_kafka == "0.8.1.1"

- name: Create upstart config
  become: yes
  template:
    dest: "{{ kafka_upstart_conf }}"
    owner: root
    group: root
    mode: 0644
    src: kafka.conf.j2
  notify:
    - restart kafka
  when: not kafka_use_systemd

- name: Create systemd config
  become: yes
  template:
    dest: "{{ kafka_systemd_service }}"
    owner: root
    group: root
    mode: 0644
    src: kafka.service.j2
  notify:
    - restart kafka
  when: kafka_use_systemd

- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  when: kafka_use_systemd

- name: Create log4j.properties
  become: yes
  become_user: "{{ kafka_user }}"
  template:
    dest: "{{ kafka_path }}/config/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart kafka

- name: Create server.properties
  become: yes
  become_user: "{{ kafka_user }}"
  template:
    dest: "{{ kafka_path }}/config/server.properties"
    mode: 0640
    src: server.properties.j2
  notify:
    - restart kafka

- name: Ensure Kafka is running
  become: yes
  service:
    name: kafka
    state: started
    enabled: yes

- name: Wait for Kafka port
  wait_for:
    port: "{{ kafka_port }}"
    state: started
    timeout: 30
