---

kafka_path                        : "/opt/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
kafka_hosts                       : "{{ groups['bi-kafka'] }}"
kafka_zookeeper_hosts             : "{{ groups['bi-zookeeper'] }}"
kafka_zookeeper_chroot            : "/bi-kafka"
kafka_version                     : "0.9.0.0"
kafka_scala_version               : "2.11"
kafka_zookeeper_port              : 2181

kafka:
  apache_mirror: http://apache.mirror.anlx.net/
  auto_create_topics: "false"
  conf_dir: "{{ kafka_path }}/config"
  data_dir: "{{ kafka_path }}/data"
  group: kafka
  heap_opts: "-Xmx{{ (ansible_memtotal_mb / 2) | int }}m -Xms{{ (ansible_memtotal_mb / 2) | int }}m"
  hosts: "{{ kafka_hosts }}"
  log_cleanup_interval_mins: 1
  log_dir: /home/kafka/log
  log_flush_interval_messages: 10000
  log_flush_interval_ms: 1000
  log_level: WARN
  log_retention_bytes: 104857600  #100 M
  log_retention_hours: 24
  log_segment_bytes: 104857600
  num_io_threads: 2
  num_network_threads: 2
  num_partitions: 2
  port: 9092
  socket_receive_buffer_bytes: 1048576
  socket_request_max_bytes: 104857600
  socket_send_buffer_bytes: 1048576
  systemd_service: /etc/systemd/system/kafka.service
  tarball_location: /home/kafka/tmp
  upstart_conf: /etc/init/kafka.conf
  use_systemd: no
  user: kafka
  version_kafka: "{{ kafka_version }}"
  version_scala: "{{ kafka_scala_version }}"
  zookeeper_connection_timeout_ms: 1000000
  zookeeper_hosts: "{{ kafka_zookeeper_hosts }}"
  zookeeper_chroot: "{{ kafka_zookeeper_chroot }}"
  zookeeper_port: "{{ kafka_zookeeper_port }}"
